version: '3'

services:
  biogrid-app:
    container_name: biogrid-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${DOCKER_EXTERNAL_PORT}:${SERVER_PORT}
    restart: unless-stopped